### ISSUE TITLE
Additional example for generating dynamic MLIR from AST would be great.

### ISSUE THREAD

**Issue by MaPePeR** [beaver-lodge/beaver#272]
I'm at a loss how to continue with my attempt at implementing a very simple Brainfuck compiler using this library.

I'm trying to generate dynamic MLIR, but to me it feels like the `mlir` macro can only be used for fixed MLIR snippets?
How to dynamically generate MLIR, e.g. from an AST?
Can one still use the `mlir` macro or does one have to use the `SSA` object directly?

And if I drop all the macro convenience and use `SSA` directly to generate e.g. a block - can I then use it inside an `mlir()` macro region (how?) or do I have to then generate everything myself without the help of the macro?

Admittedly I'm quite new to Elixir and MLIR, so it might just be a "me problem", but I think it would be great if there were more elaborate examples for that.

**Comment by jackalcooper** [comment]
Generally, it would be great if you might post some example here.

>> I'm trying to generate dynamic MLIR, but to me it feels like the mlir macro can only be used for fixed MLIR snippets?
How to dynamically generate MLIR, e.g. from an AST?

you can use any control flow constructs in Elixir within a `mlir` macro, for instance `if`, `case` etc. So it should be "dynamic"?

> And if I drop all the macro convenience and use SSA directly to generate e.g. a block - can I then use it inside an mlir() macro region (how?) or do I have to then generate everything myself without the help of the macro?

to get the current block/region the `mlir` macro, you can use `Beaver.Env.block` and `Beaver.Env.region`. The idea to mange a MLIR building context in the way kind of works like Elixir's `__MODULE__` and `__ENV__` if you have used them before

> Admittedly I'm quite new to Elixir and MLIR, so it might just be a "me problem", but I think it would be great if there were more elaborate examples for that.

Thanks for trying this! It could be very confusing because it might require understanding of some Elixir and MLIR idiom at the same time. Feel free to post any question and list what example you would like to see, so that I can reply or include it in the repo!

**Comment by jackalcooper** [comment]
> Can one still use the mlir macro or does one have to use the SSA object directly?

`mlir` macro are sugar for SSA structs. they can be mixed. In this PR there are some examples mixing them, https://github.com/beaver-lodge/beaver/pull/254/files

**Comment by MaPePeR** [comment]
Thanks you for your response.

I'm trying to use a compile function like [this](https://github.com/MaPePeR/beaver_brainfuck/blob/abb547d256f26c5a7fa3694478e86605d7a5abcc/lib/bf_dialect.ex#L12-L31):

```elixir
  def compile_ast(ssa, ast) when ast != [] do
    [op | tail] = ast
    new_ssa = case op do
      {:move_left, _} -> BeaverBrainfuck.Dialect.move_left(ssa)
      {:move_right, _} -> BeaverBrainfuck.Dialect.move_right(ssa)
      {:increment, _} -> BeaverBrainfuck.Dialect.increment(ssa)
      {:decrement, _} -> BeaverBrainfuck.Dialect.decrement(ssa)
      {:output, _} -> BeaverBrainfuck.Dialect.output(ssa)
      {:input, _} -> BeaverBrainfuck.Dialect.input(ssa)
      _ -> IO.puts("Can't handle op")
        IO.inspect(op)
        ssa
      #{:block, inside_block} -> Beaver.MLIR.Dialect.SCF.while(ssa) do: ... compile_ast(inside_block)     end
      # Not sure what the syntax is to supply two regions.
    compile_ast(new_ssa, tail)
  end
  def compile_ast(ssa, ast) when ast == [] do
    ssa
  end
```

and integrate it into an `mlir` macro [here](https://github.com/MaPePeR/beaver_brainfuck/blob/abb547d256f26c5a7fa3694478e86605d7a5abcc/beaver_bf.exs#L22-L42):

```elixir
Beaver.MLIR.CAPI.mlirContextSetAllowUnregisteredDialects(ctx, true) # How to register dialect properly?

ir =
  mlir ctx: ctx do
    module do
      Func.func main(function_type: Type.function([], [])) do
        region do
          block bb_entry() do
            # TODO: Setup Memory region
            idx = Arith.constant(value: Attribute.integer(Type.i32, 0)) >>> Type.i32()
            BeaverBrainfuck.Dialect.move_left() >>> []
            # TODO goto code.
          end

          block code() do
            BeaverBrainfuck.Dialect.compile_ast(ast) #missing argument ssa
          end
        end
      end
    end
  end
```

But that is probably not how any of this is supposed to work.

> you can use any control flow constructs in Elixir within a `mlir` macro, for instance if, case etc. So it should be "dynamic"?

I think I meant "recursive" here. Sorry, should have been more specific.

> Thanks for trying this! It could be very confusing because it might require understanding of some Elixir and MLIR idiom at the same time.

Yea. I'm noticing that. 😅 

> Feel free to post any question and list what example you would like to see, so that I can reply or include it in the repo

Thank you! I think having a Beaver version of the [toy example from the MLIR documentation](https://mlir.llvm.org/docs/Tutorials/Toy/) would be great. But that is quite elaborate, so probably a lot of work to port.

If we manage to get a brainfuck compiler working you could probably include it as an example as well.

**Comment by jackalcooper** [comment]
@MaPePeR hi, I just open a PR in your repo, hope this could answer some of your questions
https://github.com/MaPePeR/beaver_brainfuck/pull/1/files

**Comment by MaPePeR** [comment]
Thank you very very much! I will try to continue from there.

With that help I was then able to also easily [add the loops to the MLIR](https://github.com/MaPePeR/beaver_brainfuck/commit/77c8c5df210d9b9145f18a60b612d7836abb7993)! 🥳 
And I felt like I had a small epiphany on how the library and Elixir works while doing it, which was amazing.

I guess now the real adventure starts trying to lower that MLIR to something that compiles! 😄 

Or optimizing it by merging multiple increment/decrement and move operators. Though I'm curious if that is an optimization that will automatically be done if the code is properly lowered to MLIR base dialects.

Though both of that probably requires some more epiphanies to get there, so I will probably have to get back to you soon when I'm inevitable stuck again. 😅 

Thanks again!

**Comment by MaPePeR** [comment]
Before trying to lower the MLIR i tried to create an example that uses `scf.while`.

It implements this in MLIR:
```c
bool evaluate_condition(float f) {
    return f > 1;
}

float payload(float f) {
    return f / 2;
}

int work(float f) {
    int count = 0;
    while (evaluate_condition(f)) {
        f = payload(f)
        count += 1;
    }
    return count;
}
```

This is inspired by the [documentation for `scf.while`](https://mlir.llvm.org/docs/Dialects/SCFDialect/#scfwhile-scfwhileop)

<details><summary>Beaver Code</summary>

```elixir
use Beaver

alias Beaver.MLIR.Dialect.Arith
alias Beaver.MLIR.Attribute
alias Beaver.MLIR.Type
alias Beaver.MLIR.Dialect.Func
alias Beaver.MLIR.Dialect.SCF

require Func
ctx = MLIR.Context.create()

ir =
  mlir ctx: ctx do
    module do
      Func.func evaluate_condition(function_type: Type.function([Type.f32()], [Type.i1()])) do
        region do
          block _bb_entry(a >>> Type.f32()) do
            one = Arith.constant(value: Attribute.float(Type.f32(), 1.0)) >>> Type.f32()
            greater1 = Arith.cmpf(a, one, predicate: Arith.cmp_f_predicate(:ugt)) >>> Type.i1()
            Func.return(greater1) >>> []
          end
        end
      end

      Func.func payload(function_type: Type.function([Type.f32()], [Type.f32()])) do
        region do
          block _bb_entry(a >>> Type.f32()) do
            two = Arith.constant(value: Attribute.float(Type.f32(), 2.0)) >>> Type.f32()
            result = Arith.divf(a, two) >>> Type.f32()
            Func.return(result) >>> []
          end
        end
      end

      Func.func work(function_type: Type.function([Type.f32()], [Type.i32()])) do
        region do
          block _bb_entry(init1 >>> Type.f32()) do
            count = Arith.constant(value: Attribute.integer(Type.i32(), 0)) >>> Type.i32()

            [_result, count] =
              SCF.while [init1, count] do
                region do
                  block _before(arg1 >>> Type.f32(), count >>> Type.i32()) do
                    condition =
                      Func.call([arg1], callee: Attribute.flat_symbol_ref("evaluate_condition")) >>>
                        [Type.i1()]

                    SCF.condition(condition, arg1, count) >>> []
                  end
                end

                region do
                  block _after(arg2 >>> Type.f32(), count >>> Type.i32()) do
                    next =
                      Func.call([arg2], callee: Attribute.flat_symbol_ref("payload")) >>>
                        [Type.f32()]

                    one = Arith.constant(value: Attribute.integer(Type.i32(), 1)) >>> Type.i32()
                    count = Arith.addi(count, one) >>> Type.i32()
                    SCF.yield(next, count) >>> []
                  end
                end
              end >>> [Type.f32(), Type.i32()]

            Func.return(count) >>> []
          end
        end
      end
    end
  end

ir |> Beaver.MLIR.to_string() |> IO.puts()

llvm_ir =
  ir
  |> Beaver.MLIR.Conversion.convert_scf_to_cf()
  |> Beaver.MLIR.Conversion.convert_arith_to_llvm()
  |> MLIR.Pass.Composer.nested("func.func", "llvm-request-c-wrappers")
  |> Beaver.MLIR.Conversion.convert_func_to_llvm()
  |> MLIR.Pass.Composer.run!()

llvm_ir |> Beaver.MLIR.to_string() |> IO.puts()

return = Beaver.Native.I32.make(0)
arguments = [Beaver.Native.F32.make(23.0)]

jit = MLIR.ExecutionEngine.create!(llvm_ir)

MLIR.ExecutionEngine.invoke!(jit, "work", arguments, return) |> IO.inspect()

IO.inspect(Beaver.Native.to_term(return))
```

</details>

I noticed, that ` Beaver.MLIR.to_string()` falls back to the "generic assembly format" if something isn't right.
But it does at no place tell you what is wrong. This happens for example if you define a `func.func` without a `func.return`. (e.g.  remove the return in the [example in the doc](https://hexdocs.pm/beaver/your-first-beaver-compiler.html#a-taste-of-mlir))

Also happened when i did not have the `count` yet and my `scf.while` was wrongly typed as `>>> []` instead of `>>>[Type.f32]`

Would be great if there would be some warning or hint. But not sure if LLVM-MLIR provides that information.

**Comment by jackalcooper** [comment]
> I noticed, that  Beaver.MLIR.to_string() falls back to the "generic assembly format" if something isn't right.
But it does at no place tell you what is wrong. 

- You can run a verification to print some diagnostic. `op |> MLIR.Operation.verify!(debug: true)`. 
- In latest version of Beaver (which I recommend to upgrade to), you also need to call `Beaver.Diagnostic.attach(ctx)` to enable the diagnostic get printed to stderr

**Comment by jackalcooper** [comment]
Close for now, feel free to open new issues!
